### ISSUE TITLE
error with date

### ISSUE THREAD

**Issue by digitaldust** [ElsevierDev/elsapy#60]
I am running this query: 

    search_query = 'TITLE-ABS-KEY("smart working" OR "smart work" OR smartworking OR smartwork) AND SUBJAREA(ENGI) AND LOAD-DATE AFT 19800101'
    search_results = ElsSearch(search_query,  'scopus')
    search_results.execute(client, get_all = True)

and since one of the Scopus data has a weird format (1972-00-01), I get this error:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
    654         try:
    --> 655             ret = self._build_naive(res, default)
    656         except ValueError as e:

    ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in _build_naive(self, res, default)
       1240 
    -> 1241         naive = default.replace(**repl)
       1242 

    ValueError: month must be in 1..12

    The above exception was the direct cause of the following exception:

    ParserError                               Traceback (most recent call last)
    pandas/_libs/tslibs/conversion.pyx in 
    pandas._libs.tslibs.conversion.convert_str_to_tsobject()

    pandas/_libs/tslibs/parsing.pyx in pandas._libs.tslibs.parsing.parse_datetime_string()

    ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in parse(timestr, parserinfo, **kwargs)
       1373     else:
    -> 1374         return DEFAULTPARSER.parse(timestr, **kwargs)
     1375 

    ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
        656         except ValueError as e:
    --> 657             six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
       658 

     ~/opt/anaconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

    ParserError: month must be in 1..12: 1972-00-01

    During handling of the above exception, another exception occurred:

    ValueError                                Traceback (most recent call last)
    <ipython-input-49-192886904661> in <module>
      1 search_query = 'TITLE-ABS-KEY("smart working" OR "smart work" OR smartworking OR smartwork) AND SUBJAREA(ENGI) AND LOAD-DATE AFT 19800101'
      2 search_results = ElsSearch(search_query, 'scopus')
    ----> 3 search_results.execute(client, get_all = True)

    ~/opt/anaconda3/lib/python3.7/site-packages/elsapy/elssearch.py in execute(self, els_client, get_all)
        105         with open('dump.json', 'w') as f:
        106             f.write(json.dumps(self._results))
    --> 107         self.results_df = recast_df(pd.DataFrame(self._results))
        108 
        109     def hasAllResults(self):

    ~/opt/anaconda3/lib/python3.7/site-packages/elsapy/utils.py in recast_df(df)
         41             logger.info("Converting {}".format(date_field))
         42             df[date_field] = df[date_field].apply(
    ---> 43                     pd.Timestamp)
         44     return df

    ~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
       3846             else:
       3847                 values = self.astype(object).values
    -> 3848                 mapped = lib.map_infer(values, f, convert=convert_dtype)
       3849 
       3850         if len(mapped) and isinstance(mapped[0], Series):

    pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

    pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.__new__()

    pandas/_libs/tslibs/conversion.pyx in pandas._libs.tslibs.conversion.convert_to_tsobject()

    pandas/_libs/tslibs/conversion.pyx in pandas._libs.tslibs.conversion.convert_str_to_tsobject()

    ValueError: could not convert string to Timestamp

any idea how to fix this?

**Comment by giopaglia** [comment]
Hi, I have the same error, any idea?

`Traceback (most recent call last):
  File "/home/giopaglia/.local/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 649, in parse
    ret = self._build_naive(res, default)
  File "/home/giopaglia/.local/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1235, in _build_naive
    naive = default.replace(**repl)
ValueError: month must be in 1..12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pandas/_libs/tslibs/conversion.pyx", line 648, in pandas._libs.tslibs.conversion._convert_str_to_tsobject
  File "pandas/_libs/tslibs/parsing.pyx", line 257, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/home/giopaglia/.local/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/giopaglia/.local/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 651, in parse
    six.raise_from(ParserError(str(e) + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: month must be in 1..12: 1972-00-01

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "3_russell-publications.py", line 279, in <module>
    aut_srch.execute(client, get_all = True)
  File "/home/giopaglia/.local/lib/python3.8/site-packages/elsapy/elssearch.py", line 107, in execute
    self.results_df = recast_df(pd.DataFrame(self._results))
  File "/home/giopaglia/.local/lib/python3.8/site-packages/elsapy/utils.py", line 42, in recast_df
    df[date_field] = df[date_field].apply(
  File "/home/giopaglia/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4357, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/home/giopaglia/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 1043, in apply
    return self.apply_standard()
  File "/home/giopaglia/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 1098, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "pandas/_libs/tslibs/timestamps.pyx", line 1332, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "pandas/_libs/tslibs/conversion.pyx", line 407, in pandas._libs.tslibs.conversion.convert_to_tsobject
  File "pandas/_libs/tslibs/conversion.pyx", line 651, in pandas._libs.tslibs.conversion._convert_str_to_tsobject
ValueError: could not convert string to Timestamp`

**Comment by Hansbeda** [comment]
Anybody has a fix for this?

> I am running this query:
> 
> ```
> search_query = 'TITLE-ABS-KEY("smart working" OR "smart work" OR smartworking OR smartwork) AND SUBJAREA(ENGI) AND LOAD-DATE AFT 19800101'
> search_results = ElsSearch(search_query,  'scopus')
> search_results.execute(client, get_all = True)
> ```
> 
> and since one of the Scopus data has a weird format (1972-00-01), I get this error:
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
> 654         try:
> --> 655             ret = self._build_naive(res, default)
> 656         except ValueError as e:
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in _build_naive(self, res, default)
>    1240 
> -> 1241         naive = default.replace(**repl)
>    1242 
> 
> ValueError: month must be in 1..12
> 
> The above exception was the direct cause of the following exception:
> 
> ParserError                               Traceback (most recent call last)
> pandas/_libs/tslibs/conversion.pyx in 
> pandas._libs.tslibs.conversion.convert_str_to_tsobject()
> 
> pandas/_libs/tslibs/parsing.pyx in pandas._libs.tslibs.parsing.parse_datetime_string()
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in parse(timestr, parserinfo, **kwargs)
>    1373     else:
> -> 1374         return DEFAULTPARSER.parse(timestr, **kwargs)
>  1375 
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
>     656         except ValueError as e:
> --> 657             six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
>    658 
> 
>  ~/opt/anaconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)
> 
> ParserError: month must be in 1..12: 1972-00-01
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-49-192886904661> in <module>
>   1 search_query = 'TITLE-ABS-KEY("smart working" OR "smart work" OR smartworking OR smartwork) AND SUBJAREA(ENGI) AND LOAD-DATE AFT 19800101'
>   2 search_results = ElsSearch(search_query, 'scopus')
> ----> 3 search_results.execute(client, get_all = True)
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/elsapy/elssearch.py in execute(self, els_client, get_all)
>     105         with open('dump.json', 'w') as f:
>     106             f.write(json.dumps(self._results))
> --> 107         self.results_df = recast_df(pd.DataFrame(self._results))
>     108 
>     109     def hasAllResults(self):
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/elsapy/utils.py in recast_df(df)
>      41             logger.info("Converting {}".format(date_field))
>      42             df[date_field] = df[date_field].apply(
> ---> 43                     pd.Timestamp)
>      44     return df
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
>    3846             else:
>    3847                 values = self.astype(object).values
> -> 3848                 mapped = lib.map_infer(values, f, convert=convert_dtype)
>    3849 
>    3850         if len(mapped) and isinstance(mapped[0], Series):
> 
> pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()
> 
> pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.__new__()
> 
> pandas/_libs/tslibs/conversion.pyx in pandas._libs.tslibs.conversion.convert_to_tsobject()
> 
> pandas/_libs/tslibs/conversion.pyx in pandas._libs.tslibs.conversion.convert_str_to_tsobject()
> 
> ValueError: could not convert string to Timestamp
> ```
> 
> any idea how to fix this?
